//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int id { get; set; }
        public int personId { get; set; }
        public int numberId { get; set; }
        public string day { get; set; }
        public Nullable<int> roomId { get; set; }
        public int nameId { get; set; }
        public int classId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual LessonName LessonName { get; set; }
        public virtual LessonTime LessonTime { get; set; }
        public virtual Person Person { get; set; }
        public virtual Room Room { get; set; }
    }
}
