//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int classId { get; set; }
        public byte[] photo { get; set; }
        public string phone { get; set; }
        public System.DateTime birthday { get; set; }
        public string patronymic { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
